version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: myapp-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./back
    container_name: myapp-backend
    ports:
      - "5000:5000"
    volumes:
      - ./back:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/budget-tracker
    depends_on:
      - mongo

  frontend:
    build: ./front
    container_name: myapp-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./front:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
    depends_on:
      - backend

volumes:
  mongo-data:
