apiVersion: v1
kind: Secret
metadata:
  name: budgetbuddy-secrets
  namespace: budgetbuddy
type: Opaque
stringData:
  jwt-secret: "change-me-in-production"
  mongo-uri: "mongodb://mongo-service:27017/budget-tracker"
